#CAMPO DE AGRUPACION
#CAMPO DE CALCULO

SELECT SECCIÓN, 
SUM(PRECIO) AS PRECIO
FROM practicandobd.productos
GROUP BY SECCIÓN
ORDER BY PRECIO;

#####AVG
#EL HAVINF SUSTITUYE AL WHERE
SELECT SECCIÓN, 
AVG(PRECIO) AS PROMEDIO
FROM practicandobd.productos
GROUP BY SECCIÓN
HAVING SECCIÓN ='DEPORTES' OR SECCIÓN = 'CONFECCIÓN'
ORDER BY PROMEDIO;

#### COUNT
SELECT POBLACIÓN,
count(CÓDIGOCLIENTE) AS CUENTA
FROM practicandobd.clientes
group by POBLACIÓN
ORDER BY CUENTA;

### MAX
SELECT SECCIÓN,
max(PRECIO) AS MAXIMO
FROM practicandobd.productos
group by SECCIÓN
HAVING SECCIÓN = 'CONFECCIÓN';