#### 1

SELECT *
FROM practicandobd.productos
WHERE PAÍSDEORIGEN = 'ESPAÑA' AND 
(FECHA BETWEEN '2002-02-01' AND '2002-05-31')
ORDER BY NOMBREARTÍCULO DESC;

### 2 
SELECT EMPRESA, DIRECCIÓN, POBLACIÓN
FROM practicandobd.clientes
ORDER BY POBLACIÓN, DIRECCIÓN DESC;

###3 
SELECT * FROM practicandobd.clientes
ORDER BY POBLACIÓN;


### 1
SELECT DIRECCIÓN, TELÉFONO, POBLACIÓN AS RESIDENCIA
FROM practicandobd.clientes
ORDER BY RESIDENCIA DESC;

### 2
SELECT POBLACIÓN
FROM practicandobd.clientes
GROUP BY POBLACIÓN;

### 3
SELECT SECCIÓN,
SUM(PRECIO) AS SUMA,
AVG(PRECIO) AS PROMEDIO
FROM practicandobd.productos
GROUP BY SECCIÓN;

### 4
SELECT SECCIÓN,
AVG(PRECIO) AS PROMEDIO
FROM practicandobd.productos
GROUP BY SECCIÓN
HAVING SECCIÓN <> 'JUGUETERÍA';

### 5
SELECT SECCIÓN,
COUNT(CÓDIGOARTÍCULO) AS NRO
FROM practicandobd.productos
WHERE SECCIÓN = 'DEPORTES'
GROUP BY SECCIÓN;