#### CONSULTAS DE CALCULOS

#FROM practicandobd.clientes

#CALCULANDO
SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO,
PRECIO*1.18 AS IGV
FROM practicandobd.productos;

#REDONDEANDO
SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO,
ROUND(PRECIO*1.18, 2) AS IGV
FROM practicandobd.productos;

#REDONDEANDO
SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO,
ROUND(PRECIO - 5, 2) AS PRECIODESCUENTO
FROM practicandobd.productos;

#TRABJANDO CON FECHAS
SELECT NOMBREARTÍCULO, SECCIÓN, FECHA,
NOW() AS HOY,
DATE_FORMAT(NOW(), '%D-%M-%Y') AS FECHAHOY,
DATEDIFF(NOW(), FECHA) AS DIFERFECHA
FROM practicandobd.productos;